import '@testing-library/jest-dom';
import { vi } from 'vitest';

// Mock IntersectionObserver for framer-motion
class MockIntersectionObserver {
  root = null;
  rootMargin = '';
  thresholds: number[] = [];
  observe() {}
  unobserve() {}
  disconnect() {}
  takeRecords() { return []; }
}
Object.defineProperty(window, 'IntersectionObserver', {
  writable: true,
  value: MockIntersectionObserver,
});

// Mock matchMedia
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  }),
});

window.scrollTo = () => {};

// Mock react-i18next
vi.mock('react-i18next', async () => {
  const actual = await vi.importActual('react-i18next');
  return {
    ...actual,
    useTranslation: () => ({
      t: (key: string) => {
        const translations: Record<string, string> = {
          'nav.home': 'Home',
          'nav.courses': 'Courses',
          'nav.blog': 'Blog',
          'nav.about': 'About',
          'nav.contact': 'Contact',
          'nav.login': 'Login',
          'nav.register': 'Register',
          'nav.dashboard': 'Dashboard',
          'nav.admin': 'Admin',
          'nav.logout': 'Logout',
          'hero.title': 'Learn English with 28 Years of Experience',
          'hero.subtitle': 'Ahmed Fares - Diploma in Teaching English from Scotland',
          'hero.cta': 'Start Learning Now',
          'hero.secondary': 'View Courses',
          'features.title': 'Why Choose Us',
          'features.subtitle': 'We provide the best English learning experience',
          'features.courses.title': 'Comprehensive Courses',
          'features.courses.description': 'Well-structured courses covering all aspects of English for Thanaweya Amma',
          'features.live.title': 'Live Sessions',
          'features.live.description': 'Interactive online and offline sessions with expert guidance',
          'features.exams.title': 'Online Exams',
          'features.exams.description': 'Practice exams with instant grading and detailed feedback',
          'features.ai.title': 'AI-Powered Learning',
          'features.ai.description': 'Smart tools to enhance your learning experience',
          'auth.login.title': 'Welcome Back',
          'auth.login.subtitle': 'Sign in to your account',
          'auth.login.email': 'Email',
          'auth.login.password': 'Password',
          'auth.login.submit': 'Sign In',
          'auth.login.noAccount': "Don't have an account?",
          'auth.login.register': 'Register',
          'auth.register.title': 'Create Account',
          'auth.register.subtitle': 'Join Ahmed Fares English Academy',
          'auth.register.name': 'Full Name',
          'auth.register.email': 'Email',
          'auth.register.password': 'Password',
          'auth.register.phone': 'Phone (optional)',
          'auth.register.submit': 'Create Account',
          'auth.register.hasAccount': 'Already have an account?',
          'auth.register.login': 'Sign In',
          'dashboard.welcome': 'Welcome',
          'dashboard.myCourses': 'My Courses',
          'dashboard.myPayments': 'My Payments',
          'dashboard.myBookings': 'My Bookings',
          'dashboard.myCertificates': 'My Certificates',
          'dashboard.profile': 'Profile Settings',
          'dashboard.notifications': 'Notifications',
          'common.loading': 'Loading...',
          'common.error': 'Something went wrong',
          'common.save': 'Save',
          'common.cancel': 'Cancel',
          'common.delete': 'Delete',
          'common.edit': 'Edit',
          'common.view': 'View',
          'common.search': 'Search...',
          'common.noData': 'No data found',
          'common.confirm': 'Are you sure?',
          'common.back': 'Back',
          'common.next': 'Next',
          'common.submit': 'Submit',
          'common.not_found': 'Not Found',
          'common.go_home': 'Go Home',
          'common.go_back': 'Go Back',
          'common.page_not_found': 'Page Not Found',
          'common.page_not_found_desc': 'Sorry, the page you are looking for does not exist or has been moved.',
          'hero.badge': 'Ahmed Fares - 28 Years Experience',
          'hero.about_us': 'About Us',
          'hero.beni_suef': 'Beni Suef',
          'hero.student_rating': 'Student Rating',
          'cta_section.register_free': 'Register Now Free',
          'cta_section.browse_courses': 'Browse Courses',
          'seo.default.title': 'Ahmed Fares English Academy',
          'seo.default.description': 'Premium English learning platform',
          'seo.home.title': 'Home',
          'seo.home.description': 'Home page',
          'seo.home.keywords': 'english',
          'seo.notFound.title': 'Page Not Found',
          'seo.blog.keywords': 'blog',
          'courses.hero_title': 'Our Courses',
          'courses.hero_subtitle': 'Explore our courses',
          'courses.search_placeholder': 'Search...',
          'courses.no_courses': 'No Courses Yet',
          'courses.no_courses_desc': 'Coming soon',
          'courses.chapters_count': 'chapters',
          'courses.lessons_count': 'Lessons',
          'courses.free': 'Free',
          'courses.enrolled': 'Enrolled',
          'courses.enroll_now': 'Enroll Now',
          'courses.login_to_enroll': 'Login to Enroll',
          'courses.course_content': 'Course Content',
          'courses.content_coming_soon': 'Coming soon',
          'courses.min': 'min',
          'courses.no_lessons': 'No lessons yet',
          'courses.back_to_courses': 'Back to Courses',
          'courses.course_not_found': 'Course Not Found',
          'courses.questions': 'questions',
          'blog.hero_title': 'Blog',
          'blog.hero_subtitle': 'Articles and tips',
          'blog.search_placeholder': 'Search...',
          'blog.no_posts': 'No Posts Yet',
          'blog.no_posts_desc': 'Coming soon',
          'blog.author': 'Ahmed Fares',
          'blog.read_more': 'Read More',
          'blog.back_to_blog': 'Back to Blog',
          'blog.post_not_found': 'Post Not Found',
          'contact.hero_title': 'Contact Us',
          'contact.hero_subtitle': 'We are here to help',
          'contact.send_message': 'Send a Message',
          'contact.message_sent': 'Message Sent!',
          'contact.message_sent_desc': 'We will reply soon.',
          'contact.form_name': 'Name',
          'contact.form_email': 'Email',
          'contact.form_phone': 'Phone',
          'contact.form_subject': 'Subject',
          'contact.form_message': 'Message',
          'contact.form_submit': 'Send Message',
          'contact.chat_whatsapp': 'Chat on WhatsApp',
          'contact.whatsapp_desc': 'Quick response',
          'contact.map_title': 'Our Location',
          'info.phoneTitle': 'Phone',
          'info.locationTitle': 'Location',
          'info.hoursTitle': 'Hours',
          'info.hoursValue': 'Sat-Thu: 10AM-8PM',
          'info.address': 'Beni Suef',
          'info.mapTitle': 'Map',
          'about.hero_title': 'About Us',
          'about.hero_subtitle': 'Learn about Ahmed Fares',
          'about.journey_title': 'A Journey Full of Success',
          'about.journey_p1': 'Ahmed Fares is an English teacher.',
          'about.journey_p2': 'He is committed to providing the best.',
          'about.experience_title': 'Experience & Qualifications',
          'about.schools_title': 'Schools',
          'about.schools_subtitle': 'Schools where Ahmed Fares worked',
          'about.values_title': 'Our Values',
          'about.teacher_name': 'Ahmed Fares',
          'about.teacher_role': 'English Teacher',
          'about.experience_28_years': '28 Years Experience',
          'about.diploma_scotland': 'Diploma from Scotland',
          'about.location_beni_suef': 'Beni Suef',
          'about.years_experience': 'Years Experience',
          'about.students_stat': 'Students',
          'contact.form.successTitle': 'Success!',
          'contact.form.successDescription': 'We will reply.',
          'contact.form.title': 'Send Message',
          'header.dark_mode': 'Dark mode',
          'header.light_mode': 'Light mode',
          'header.academy_name': 'Ahmed Fares Academy',
          'lesson.previous': 'Previous',
          'lesson.next': 'Next',
          'lesson.backToCourse': 'Back to Course',
          'lesson.noContent': 'No content available yet',
          'lesson.chapter': 'Chapter',
          'lesson.free': 'Free',
          'lesson.completed': 'Completed ✓',
          'lesson.mark_complete': 'Mark Complete',
          'exam.startExam': 'Start Exam',
          'exam.question': 'Question',
          'exam.previous': 'Previous',
          'exam.next': 'Next',
          'exam.submit': 'Submit Exam',
          'exam.passed': 'Congratulations! You Passed',
          'exam.notPassed': 'Not Passed',
          'exam.correctAnswers': 'correct answers',
          'exam.passingScore': 'Passing score',
          'exam.retry': 'Retry',
          'exam.attempts': 'attempts',
          'exam.exam_not_found': 'Exam not found',
          'exam.exam_result': 'Exam Result',
          'exam.duration_min': 'min',
          'admin.dashboard': 'Admin Dashboard',
          'admin.users': 'Users',
          'admin.courses': 'Courses',
          'admin.payments': 'Payments',
          'admin.bookings': 'Bookings',
          'admin.blog': 'Blog',
          'admin.announcements': 'Announcements',
          'admin.exams': 'Exams',
          'admin.sendNotifications': 'Notifications',
          'admin.settings': 'Settings',
          'admin.backToStudent': 'Back to Dashboard',
          'admin.totalUsers': 'Total Users',
          'admin.totalCourses': 'Total Courses',
          'admin.totalRevenue': 'Total Revenue',
          'admin.totalBookings': 'Total Bookings',
          'admin.pendingPayments': 'Pending Payments',
          'admin.totalEnrollments': 'Total Enrollments',
          'admin.totalCertificates': 'Total Certificates',
          'admin.totalBlogPosts': 'Blog Posts',
          'footer.description': 'Premium English learning platform for Egyptian Thanaweya Amma students',
          'footer.quickLinks': 'Quick Links',
          'footer.contact': 'Contact Us',
          'footer.followUs': 'Follow Us',
          'footer.rights': 'All rights reserved',
        };
        return translations[key] || key;
      },
      i18n: { language: 'en', changeLanguage: vi.fn() },
    }),
    Trans: ({ children }: any) => children,
  };
});
